// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:habitroot/features/habit/domain/habit.dart';
import 'package:habitroot/features/notification/domain/reminder.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HabitAdapter());
    registerAdapter(ReminderAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HabitAdapter());
    registerAdapter(ReminderAdapter());
  }
}
